spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: <GOOGLE ID>
            clientSecret: <GOOGLE SECRET>
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
          github:
            clientId: <GITHUB ID>
            clientSecret: <GITHUB SECRET>
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - user:email
              - read:user